### PR TITLE
Allow sandbox to be false

### PR DESCRIPTION
**Pull request by crevillo**
ping @makasim

### CODE REVIEW

**Comment by makasim** [comment]
I dont like it. I prefer to force users to set it explicitly, for example you leave it empty accidentally and you go to production environment and later you realized that it is not what you want.

**Comment by crevillo** [comment]
the thing is when i set it to false i got an error saying
``` 
[Symfony\Component\Config\Definition\Exception\InvalidConfigurationException]                  
  The path "payum.payments.redsys.redsys.sandbox" cannot contain an empty value, but got false.
```

It seems false is evaluated to empty somewhere?

**Comment by makasim** [comment]
let's do it this way https://github.com/Payum/PayumBundle/blob/master/DependencyInjection/Factory/Payment/PaypalExpressCheckoutNvpPaymentFactory.php#L27

**Comment by crevillo** [comment]
done.

**Comment by crevillo** [comment]
merging

**Comment by crevillo** [comment]
maybe should i backport this to 0.13?

**Comment by makasim** [comment]
> maybe should i backport this to 0.13?

If you personally need then you can backport it. I dont support outdate version (which is 0.13) only stable 0.14 and master

**Pull request merged**
