### PR TITLE
[WIP] Rename Payment to Gateway and Order to Payment

### PR DESCRIPTION
**Pull request by makasim**
Based on https://github.com/Payum/Payum/pull/347

### CODE REVIEW

**Comment by crevillo** [comment]
no time to check it properly but looks good for me at first. i'll be almost totally out until monday because my brother's weeding :). feel free to merge if you are confortable with it.

**Comment by makasim** [comment]
It will wait for you ;)

**Comment by makasim** [comment]
@crevillo merged.

**Comment by crevillo** [comment]
duh! i forgot. Cool, Thanks!

**Pull request merged**
